# Generated by Django 5.2.3 on 2025-11-09 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco_level', models.CharField(default='Beginner', max_length=50)),
                ('user_points', models.IntegerField(default=0)),
                ('waste_recycled', models.CharField(default='0 kg', max_length=50)),
                ('distance_biked', models.CharField(default='0 km', max_length=50)),
                ('solar_hours', models.CharField(default='0 hrs', max_length=50)),
                ('sustain_score', models.CharField(default='0%', max_length=10)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
